Use common build steps, update runs-on

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,27 +8,40 @@ on:
     - cron: '30 5 * * 3'
 
 env:
-  OCTAVE_VERSION: 6.4.0
+  OCTAVE_VERSION: 8.3.0
   ARCH: x86_64
 
 jobs:
-  build-macos:
-    runs-on: 'macos-10.15'
-    name: Build on MacOS
+  build:
+    strategy:
+      matrix:
+        os: ['macos-11', 'macos-12', 'ubuntu-22.04']
+    runs-on: ${{ matrix.os }}
+    name: Build on ${{ runner.os }}
     steps:
       # https://github.com/actions/checkout
       - name: Checkout the commit triggering this job
         uses: actions/checkout@v4
 
       - name: Update Homebrew
+        if: runner.os == 'macOS'
         run: |
           brew update --preinstall
           echo "::notice title=BrewPrefix::$(brew --prefix)"
           echo "::notice title=BrewCache::$(brew --cache)"
 
+      # https://wiki.octave.org/Octave_for_Debian_systems#The_right_way
+      # https://github.com/actions/virtual-environments/issues/2924
+      - name: Install dependencies (Ubuntu)
+        if: runner.os == 'Linux'
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y gcc g++ gfortran make libblas-dev liblapack-dev libpcre3-dev libarpack2-dev libcurl4-gnutls-dev epstool libfftw3-dev fig2dev libfltk1.3-dev libfontconfig1-dev libfreetype6-dev libgl2ps-dev libglpk-dev libreadline-dev gnuplot-x11 libgraphicsmagick++1-dev libhdf5-dev openjdk-11-jdk libsndfile1-dev llvm-dev texinfo libgl1-mesa-dev pstoedit portaudio19-dev libqhull-dev libqrupdate-dev libsuitesparse-dev texlive-latex-extra libxft-dev zlib1g-dev autoconf automake bison flex gperf gzip icoutils librsvg2-bin libtool perl rsync tar qtbase5-dev qttools5-dev qttools5-dev-tools libqscintilla2-qt5-dev libsundials-dev
+
         # THX https://github.com/jawang35/dotfiles/blob/master/.github/workflows/ci.yml#L16
         # https://github.com/actions/cache
       - name: Cache Homebrew Packages
+        if: runner.os == 'macOS'
         id: cache-homebrew-packages
         uses: actions/cache@v3
         env:
@@ -108,7 +121,7 @@ jobs:
             octave-download-cachev2-${{ env.OCTAVE_VERSION }}
 
       - name: Install dependencies (MacOS)
-        if: steps.cache-homebrew-packages.output.cache-hit != 'true'
+        if: runner.os == 'macOS' && steps.cache-homebrew-packages.output.cache-hit != 'true'
         run: |
           brew bundle --file="$GITHUB_WORKSPACE/Brewfile"
         env:
@@ -122,6 +135,7 @@ jobs:
           tar -xJf octave-$OCTAVE_VERSION.tar.xz --directory $GITHUB_WORKSPACE
 
       - name: Configure Octave ${{ env.OCTAVE_VERSION }}
+        if: runner.os == 'macOS'
         run: |
           export BREWPFX=`brew --prefix`
           cd $GITHUB_WORKSPACE/octave-$OCTAVE_VERSION
@@ -153,6 +167,7 @@ jobs:
           QCOLLECTIONGENERATOR: qhelpgenerator
 
       - name: Build Octave
+        if: runner.os == 'macOS'
         run: |
           export BREWPFX=`brew --prefix`
           export CPPFLAGS="$CPPFLAGS -I$BREWPFX/include -I$BREWPFX/opt/readline/include -I$BREWPFX/opt/bison/include -I$BREWPFX/opt/texinfo/include"
@@ -165,48 +180,17 @@ jobs:
           make octave-config.h || echo "::warning title=OctaveConfigFailure::Failed to build octave-config.h"
           make -j2 all || echo "::warning title=BuildFailure::Build Failed"
 
-  build-ubuntu:
-    runs-on: 'ubuntu-20.04'
-    name: Build on Ubuntu
-    steps:
-      # https://github.com/actions/checkout
-      - name: Checkout the commit triggering this job
-        uses: actions/checkout@v4
-
-      # https://wiki.octave.org/Octave_for_Debian_systems#The_right_way
-      # https://github.com/actions/virtual-environments/issues/2924
-      - name: Install dependencies (Ubuntu)
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y gcc g++ gfortran make libblas-dev liblapack-dev libpcre3-dev libarpack2-dev libcurl4-gnutls-dev epstool libfftw3-dev fig2dev libfltk1.3-dev libfontconfig1-dev libfreetype6-dev libgl2ps-dev libglpk-dev libreadline-dev gnuplot-x11 libgraphicsmagick++1-dev libhdf5-dev openjdk-11-jdk libsndfile1-dev llvm-dev texinfo libgl1-mesa-dev pstoedit portaudio19-dev libqhull-dev libqrupdate-dev libsuitesparse-dev texlive-latex-extra libxft-dev zlib1g-dev autoconf automake bison flex gperf gzip icoutils librsvg2-bin libtool perl rsync tar qtbase5-dev qttools5-dev qttools5-dev-tools libqscintilla2-qt5-dev libsundials-dev
-
-      - name: Cache Octave Download
-        id: cache-octave-download
-        uses: actions/cache@v3
-        env:
-          cache-name: octave-download
-        with:
-          path: |
-            octave-*.tar.gz
-            octave-*/**
-          key:
-            octave-download-cachev2-${{ env.OCTAVE_VERSION }}
-
-      # https://www.gnu.org/software/octave/
-      - name: Grab Octave Source v${{ env.OCTAVE_VERSION }}
-        if: steps.cache-octave-download.outputs.cache-hit != 'true'
-        run: |
-          curl -o octave-$OCTAVE_VERSION.tar.xz https://ftp.gnu.org/gnu/octave/octave-$OCTAVE_VERSION.tar.xz
-          tar -xJf octave-$OCTAVE_VERSION.tar.xz --directory $GITHUB_WORKSPACE
-
       - name: Configure Octave ${{ env.OCTAVE_VERSION }}
+        if: runner.os == 'Linux'
         run: |
           cd $GITHUB_WORKSPACE/octave-$OCTAVE_VERSION
-          ./configure --prefix=$GITHUB_WORKSPACE/usr
+          ./configure --prefix=$GITHUB_WORKSPACE/usr \
+          || (cat config.log ; echo "::warning title=ConfigureFailure::Configure Failed")
 
       # Why aren't the necessary header files being generated? Not clear...
       # Grabbed these from the Makefile SMX_OP_INC, VX_OP_INC, MX_OP_INC, LIBOCTAVE_OPT_INC
       - name: Build Octave
+        if: runner.os == 'Linux'
         run: |
           cd $GITHUB_WORKSPACE/octave-$OCTAVE_VERSION
           make octave-config.h || echo "::warning title=OctaveConfigFailure::Failed to build octave-config.h"
