Add build directory to include path listing
Specify qhull directories

Force build of octave-config.h before building the rest of the project

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -97,12 +97,13 @@ jobs:
             --with-hdf5-libdir=$BREWPFX/lib \
             --with-java-homedir=$BREWPFX/opt/openjdk \
             --with-blas="-L$BREWPFX/opt/openblas -lopenblas" \
-            CPPFLAGS="$CPPFLAGS -I$BREWPFX/opt/qt/include -I$BREWPFX/include -I$BREWPFX/opt/readline/include -I$BREWPFX/opt/texinfo/lib" \
+            --with-qhull-includedir=$BREWPFX/include \
+            --with-qhull-libdir=$BREWPFX/lib \
+            CPPFLAGS="$CPPFLAGS -I$BREWPFX/opt/qt/include -I$BREWPFX/include -I$BREWPFX/opt/readline/include -I$BREWPFX/opt/texinfo/include -I$GITHUB_WORKSPACE/octave-$OCTAVE_VERSION" \
             LDFLAGS="$LDFLAGS -L$BREWPFX/opt/qt/lib -L$BREWPFX/lib -L$BREWPFX/opt/readline/lib -L$BREWPFX/opt/bison/lib -L$BREWPFX/opt/texinfo/lib" \
-            PATH=$GITHUB_WORKSPACE/usr/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/opt/bison/bin:/usr/local/opt/texinfo/bin:/usr/local/opt/qt/bin:$BREWPFX/libexec/bin:$BREWPFX/bin \
+            PATH=$GITHUB_WORKSPACE/usr/bin:/bin:/sbin:/usr/bin:/usr/sbin:$BREWPFX/opt/bison/bin:$BREWPFX/opt/texinfo/bin:$BREWPFX/opt/qt/bin:$BREWPFX/libexec/bin:$BREWPFX/bin \
             QT_CPPFLAGS=-I$BREWPFX/opt/qt/include \
             F77=$BREWPFX/bin/gfortran-11 \
-            FC=$BREWPFX/bin/gfortran-11 \
             QT_LDFLAGS=-L$BREWPFX/opt/qt/lib \
             || (cat config.log ; echo "::warning title=ConfigureFailure::Configure Failed")
         env:
@@ -111,14 +112,14 @@ jobs:
       - name: Build Octave
         run: |
           export BREWPFX=`brew --prefix`
-          export CPPFLAGS="$CPPFLAGS -I$BREWPFX/opt/qt/include -I$BREWPFX/include -I$BREWPFX/opt/readline/include -I$BREWPFX/opt/texinfo/lib"
+          export CPPFLAGS="$CPPFLAGS -I$BREWPFX/opt/qt/include -I$BREWPFX/include -I$BREWPFX/opt/readline/include -I$BREWPFX/opt/bison/include -I$BREWPFX/opt/texinfo/include -I$GITHUB_WORKSPACE/octave-$OCTAVE_VERSION"
           export LDFLAGS="$LDFLAGS -L$BREWPFX/opt/qt/lib -L$BREWPFX/lib -L$BREWPFX/opt/readline/lib -L$BREWPFX/opt/bison/lib -L$BREWPFX/opt/texinfo/lib"
-          export PATH=$GITHUB_WORKSPACE/usr/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/opt/bison/bin:/usr/local/opt/texinfo/bin:/usr/local/opt/qt/bin:$BREWPFX/libexec/bin:$BREWPFX/bin
+          export PATH=$GITHUB_WORKSPACE/usr/bin:/bin:/sbin:/usr/bin:/usr/sbin:$BREWPFX/opt/bison/bin:$BREWPFX/opt/texinfo/bin:$BREWPFX/opt/qt/bin:$BREWPFX/libexec/bin:$BREWPFX/bin
           export QT_CPPFLAGS=-I$BREWPFX/opt/qt/include
           export F77=$BREWPFX/bin/gfortran-11
-          export FC=$BREWPFX/bin/gfortran-11
           export QT_LDFLAGS=-L$BREWPFX/opt/qt/lib
           cd $GITHUB_WORKSPACE/octave-$OCTAVE_VERSION
+          make octave-config.h || echo "::warning title=OctaveConfigFailure::Failed to build octave-config.h"
           make -j2 all-local || echo "::warning title=BuildFailure::Build Failed"
 
   build-ubuntu:
@@ -163,4 +164,5 @@ jobs:
       - name: Build Octave
         run: |
           cd $GITHUB_WORKSPACE/octave-$OCTAVE_VERSION
+          make octave-config.h || echo "::warning title=OctaveConfigFailure::Failed to build octave-config.h"
           make -j2 all-local || echo "::warning title=BuildFailure::Build Failed"
