Cache octave download (nicer to GNU) and re-enable build now that we have a Homebrew cache

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -27,6 +27,7 @@ jobs:
           echo "::notice title=BrewCache::$(brew --cache)"
 
         # THX https://github.com/jawang35/dotfiles/blob/master/.github/workflows/ci.yml#L16
+        # https://github.com/actions/cache
       - name: Cache Homebrew Packages
         id: cache-homebrew-packages
         uses: actions/cache@v3
@@ -48,12 +49,22 @@ jobs:
             /usr/local/libexec
             /usr/local/include
             ~/Library/Caches/Homebrew
-          key: ${{ runner.os }}-cachev1-${{ hashFiles('Brewfile', '.github/brew-formulae') }}
+          key: ${{ runner.os }}-cachev1-${{ hashFiles('Brewfile') }}
           restore-keys: |
             ${{ runner.os }}-cachev1-
-            ${{ runner.os }}-cachev1-${{ hashFiles('Brewfile', '.github/brew-formulae') }}
+            ${{ runner.os }}-cachev1-${{ hashFiles('Brewfile') }}
 
-
+      - name: Cache Octave Download
+        id: cache-octave-download
+        uses: actions/cache@v3
+        env:
+          cache-name: octave-download
+        with:
+          path: |
+            octave-$OCTAVE_VERSION.tar.xz
+            $GITHUB_WORKSPACE/octave-$OCTAVE_VERSION
+          key:
+            octave-download-cachev1-${{ env.OCTAVE_VERSION }}
 
       - name: Install dependencies (MacOS)
         run: |
@@ -61,33 +72,34 @@ jobs:
         env:
           HOMEBREW_NO_AUTO_UPDATE: 1
 
-      #   # https://www.gnu.org/software/octave/
-      # - name: Grab Octave Source v${{ env.OCTAVE_VERSION }}
-      #   run: |
-      #     curl -o octave-$OCTAVE_VERSION.tar.xz https://ftp.gnu.org/gnu/octave/octave-$OCTAVE_VERSION.tar.xz
-      #     tar -xJf octave-$OCTAVE_VERSION.tar.xz --directory $GITHUB_WORKSPACE
+        # https://www.gnu.org/software/octave/
+      - name: Grab Octave Source v${{ env.OCTAVE_VERSION }}
+        if: steps.cache-octave-download.outputs.cache-hit != 'true'
+        run: |
+          curl -o octave-$OCTAVE_VERSION.tar.xz https://ftp.gnu.org/gnu/octave/octave-$OCTAVE_VERSION.tar.xz
+          tar -xJf octave-$OCTAVE_VERSION.tar.xz --directory $GITHUB_WORKSPACE
 
-      # - name: Configure Octave ${{ env.OCTAVE_VERSION }}
-      #   run: |
-      #     export BREWPFX=`brew --prefix`
-      #     export CPPFLAGS="$CPPFLAGS -I/usr/local/opt/qt/include"
-      #     export LDFLAGS="$LDFLAGS -L/usr/local/opt/qt/lib"
-      #     export PATH=$GITHUB_WORKSPACE/usr/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/opt/bison/bin:/usr/local/opt/texinfo/bin:/usr/local/opt/qt/bin:$BREWPFX/libexec/bin:$BREWPFX/bin
-      #     env
-      #     cd $GITHUB_WORKSPACE/octave-$OCTAVE_VERSION
-      #     autoreconf -i -f
-      #     ./configure --prefix=$GITHUB_WORKSPACE/usr --disable-dependency-tracking --disable-silent-rules --enable-link-all-dependencies --enable-shared --disable-static --with-x=no --with-portaudio --with-sndfile --with-hdf5-includedir=$BREWPFX/include --with-hdf5-libdir=$BREWPFX/lib --with-java-homedir=$BREWPFX/opt/openjdk --with-blas="-L$BREWPFX/opt/openblas -lopenblas" || (cat config.log ; echo "::warning title=ConfigureFailure::Configure Failed")
-      #   env:
-      #     QCOLLECTIONGENERATOR: qhelpgenerator
-      #     QT_CPPFLAGS: -I/usr/local/opt/qt/include
-      #     QT_LDFLAGS: -L/usr/local/opt/qt/lib
-      #     F77: /usr/local/bin/gfortran
-      #     FC: /usr/local/bin/gfortran
-      #     # CC: /usr/local/bin/gcc
+      - name: Configure Octave ${{ env.OCTAVE_VERSION }}
+        run: |
+          export BREWPFX=`brew --prefix`
+          export CPPFLAGS="$CPPFLAGS -I/usr/local/opt/qt/include"
+          export LDFLAGS="$LDFLAGS -L/usr/local/opt/qt/lib"
+          export PATH=$GITHUB_WORKSPACE/usr/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/opt/bison/bin:/usr/local/opt/texinfo/bin:/usr/local/opt/qt/bin:$BREWPFX/libexec/bin:$BREWPFX/bin
+          env
+          cd $GITHUB_WORKSPACE/octave-$OCTAVE_VERSION
+          autoreconf -i -f
+          ./configure --prefix=$GITHUB_WORKSPACE/usr --disable-dependency-tracking --disable-silent-rules --enable-link-all-dependencies --enable-shared --disable-static --with-x=no --with-portaudio --with-sndfile --with-hdf5-includedir=$BREWPFX/include --with-hdf5-libdir=$BREWPFX/lib --with-java-homedir=$BREWPFX/opt/openjdk --with-blas="-L$BREWPFX/opt/openblas -lopenblas" || (cat config.log ; echo "::warning title=ConfigureFailure::Configure Failed")
+        env:
+          QCOLLECTIONGENERATOR: qhelpgenerator
+          QT_CPPFLAGS: -I/usr/local/opt/qt/include
+          QT_LDFLAGS: -L/usr/local/opt/qt/lib
+          F77: /usr/local/bin/gfortran
+          FC: /usr/local/bin/gfortran
+          # CC: /usr/local/bin/gcc
 
-      # - name: Build Octave
-      #   run: |
-      #     make -j2 || echo "::warning title=BuildFailure::Build Failed"
+      - name: Build Octave
+        run: |
+          make -j2 || echo "::warning title=BuildFailure::Build Failed"
 
   # build-ubuntu:
   #   runs-on: 'ubuntu-20.04'
